security:
  oauth2:
    client:
      clientId: ***yourıd
      clientSecret: yoursecret
      accessToken-Uri: https://graph.facebook.com/oauth/access_token
      userAuthorization-Uri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
